images:
- dockerfile_path: Dockerfile
  to: oadp-non-admin
promotion:
  to:
  - name: oadp-non-admin
    namespace: konveyor
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: master
  org: migtools
  repo: oadp-non-admin
